service:
  name: "development-service"
  domain: "dev.example.org"

agent:
  socketPath: "/run/sockets/agent.sock"

security:
  # WARNING: This is ONLY for development environments
  # Certificate validation is disabled - NOT secure for production
  certificate_validation_disabled: true