service:
  name: "development-service"
  domain: "dev.example.org"

spiffe:
  socketPath: "/tmp/spire-agent/public/api.sock"

security:
  # WARNING: This is ONLY for development environments
  # Certificate validation is disabled - NOT secure for production
  certificate_validation_disabled: true