service:
  name: "development-service"
  domain: "dev.example.org"

agent:
  socketPath: "/run/sockets/agent.sock"

security:
  # Development only: Certificate validation disabled for local testing
  # Production environments automatically ignore this setting
  certificate_validation_disabled: true