# Renovate Alternative Configuration
# Provides additional dependency update capabilities beyond Dependabot

name: Renovate Dependencies

on:
  schedule:
    # Run weekly on Sundays at 4 AM UTC (complementing Dependabot's Monday schedule)
    - cron: '0 4 * * 0'
  workflow_dispatch:
    inputs:
      log_level:
        description: 'Renovate log level'
        required: false
        default: 'info'
        type: choice
        options:
          - 'debug'
          - 'info'
          - 'warn'
          - 'error'

# Restrict permissions for security - deny by default, allow only specific permissions per job
permissions: {}

jobs:
  renovate:
    name: Renovate Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Self-hosted Renovate
      uses: renovatebot/github-action@b9486e7c1b8a59f1e2c8c7b9b3d25a8b1e1dccaf # v40.3.11
      with:
        configurationFile: .github/renovate.json5
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        LOG_LEVEL: ${{ inputs.log_level || 'info' }}
        RENOVATE_REPOSITORIES: "sufield/ephemos"
        # Additional security configurations
        RENOVATE_REQUIRE_CONFIG: 'required'
        RENOVATE_IGNORE_UNSTABLE: 'true'
        RENOVATE_RESPECT_LATEST: 'true'