name: SAST Scan with ShiftLeft

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SCAN_WORKSPACE: "https://github.com/sufield/ephemos"

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Perform ShiftLeft Scan
        uses: ShiftLeftSecurity/scan-action@77e5a8bf896d471c59b57c9c6230cd78e7de4c9a # Fixed commit
        with:
          type: "credscan,go,depscan"  # credscan for secrets, go for SAST on Go code, depscan for dependencies
        env:
          WORKSPACE: ${{ env.SCAN_WORKSPACE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCAN_AUTO_BUILD: true

      - name: Upload scan reports
        if: always()
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: scan-reports
          path: reports/