name: YAML Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
    paths:
      - '**.yml'
      - '**.yaml'

jobs:
  yaml-validation:
    name: Validate YAML Files
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Set up yq
      uses: mikefarah/yq@c35ec752e38ea0c096d3c44e13cfc0797ac394d8 # v4.44.3

    - name: Validate GitHub workflow files
      run: |
        echo "=== Validating GitHub workflow files ==="
        find .github -name "*.yml" -o -name "*.yaml" | while read file; do
          echo "Validating: $file"
          if ! yq eval . "$file" > /dev/null 2>&1; then
            echo "❌ YAML validation failed for: $file"
            yq eval . "$file" 2>&1 | head -5
            exit 1
          else
            echo "✅ $file"
          fi
        done

    - name: Validate configuration files
      run: |
        echo "=== Validating configuration YAML files ==="
        config_files=(
          "./config/templates/k8s/configmap.yaml"
          "./config/transport-http.yaml" 
          "./config/ephemos.yaml"
          "./.golangci.yml"
          "./.goreleaser.yaml"
        )
        
        for file in "${config_files[@]}"; do
          if [ -f "$file" ]; then
            echo "Validating: $file"
            if ! yq eval . "$file" > /dev/null 2>&1; then
              echo "❌ YAML validation failed for: $file"
              yq eval . "$file" 2>&1 | head -5
              exit 1
            else
              echo "✅ $file"
            fi
          else
            echo "⚠️  File not found: $file (skipping)"
          fi
        done

    - name: Check for heredoc indentation issues
      run: |
        echo "=== Checking for common YAML indentation issues ==="
        
        # Check for heredoc blocks that might not be properly indented
        if grep -r "<<.*EOF" .github/workflows/ | while read line; do
          file=$(echo "$line" | cut -d: -f1)
          line_num=$(echo "$line" | cut -d: -f2)
          echo "Found heredoc in $file at line $line_num"
          
          # Check if the content after heredoc is properly indented
          next_line=$((line_num + 1))
          if sed -n "${next_line}p" "$file" | grep -q "^[^ ]"; then
            echo "⚠️  Potential indentation issue in $file around line $next_line"
            echo "   Heredoc content should be indented to match YAML structure"
          fi
        done; then
          echo "✅ No obvious heredoc indentation issues found"
        fi

    - name: Validate actionlint compatibility
      run: |
        echo "=== Running actionlint validation ==="
        # Install actionlint
        wget -q https://github.com/rhysd/actionlint/releases/latest/download/actionlint_linux_amd64.tar.gz
        tar xf actionlint_linux_amd64.tar.gz
        chmod +x actionlint
        
        # Validate all workflow files
        find .github/workflows -name "*.yml" | while read file; do
          echo "ActionLint validation: $file"
          if ! ./actionlint "$file"; then
            echo "❌ ActionLint validation failed for: $file"
            exit 1
          else
            echo "✅ $file passed actionlint"
          fi
        done

    - name: Generate validation summary
      if: always()
      run: |
        echo "## YAML Validation Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Files Validated" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        find .github -name "*.yml" -o -name "*.yaml" | wc -l > /tmp/github_count
        find . -maxdepth 3 -name "*.yml" -o -name "*.yaml" | grep -v .github | wc -l > /tmp/other_count
        
        echo "- GitHub workflows and configs: $(cat /tmp/github_count) files" >> $GITHUB_STEP_SUMMARY
        echo "- Project configuration files: $(cat /tmp/other_count) files" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Validation Tools Used" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **yq**: YAML parsing and validation" >> $GITHUB_STEP_SUMMARY
        echo "- **actionlint**: GitHub Actions workflow validation" >> $GITHUB_STEP_SUMMARY
        echo "- **Custom checks**: Heredoc indentation validation" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "✅ All YAML files validated successfully" >> $GITHUB_STEP_SUMMARY